# Generated by Django 5.2.5 on 2025-09-07 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EduTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('daycare', 'Daycare'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('alevel', 'Advanced Level'), ('college', 'College'), ('university', 'University')], max_length=20)),
                ('category', models.CharField(choices=[('study', 'Study & Notes'), ('productivity', 'Productivity'), ('creativity', 'Creativity & Design'), ('career', 'Career & Skills'), ('teacher', 'Teacher Tools')], max_length=50)),
                ('logo', models.ImageField(upload_to='tools/')),
                ('link', models.URLField()),
                ('is_affiliate', models.BooleanField(default=False)),
                ('affiliate_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EduToolComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='edutools.edutool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EduToolVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='edutools.edutool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tool', 'user')},
            },
        ),
    ]
