# Generated by Django 5.2.5 on 2025-09-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edutools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edutool',
            name='level',
            field=models.CharField(choices=[('daycare', 'Daycare'), ('primary', 'Primary'), ('olevel', 'Ordinary Level'), ('alevel', 'Advanced Level'), ('college', 'College'), ('university', 'University')], max_length=20),
        ),
    ]
