# Generated by Django 5.2.5 on 2025-09-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('institution_user', 'Institution User'), ('regular_user', 'Regular User'), ('vendor_user', 'Vendor User')], default='regular_user', max_length=20),
        ),
    ]
