# Generated by Django 5.2.5 on 2025-09-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_platforms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineplatform',
            old_name='website',
            new_name='link',
        ),
    ]
