# Generated by Django 5.2.5 on 2025-09-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_servicevote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorservice',
            name='district',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorservice',
            name='region',
            field=models.CharField(blank=True, null=True),
        ),
    ]
