# Generated by Django 5.2.5 on 2025-09-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendorservice_district_vendorservice_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorservice',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_services/logos/'),
        ),
    ]
