# Generated by Django 5.2.5 on 2025-09-05 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutionacademicdetail',
            name='institution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_detail', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='institutioncombination',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='institutioncurriculum',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.curriculum'),
        ),
        migrations.AddField(
            model_name='institutioncurriculum',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='institutionprogram',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='institutionservice',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='institutionsubject',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='institutionservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.service'),
        ),
        migrations.AddField(
            model_name='institutionsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.subject'),
        ),
        migrations.AddField(
            model_name='combination',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='combinations', to='institutions.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='institutioncombination',
            unique_together={('institution', 'combination')},
        ),
        migrations.AlterUniqueTogether(
            name='institutionsubject',
            unique_together={('institution', 'subject')},
        ),
    ]
