# Generated by Django 5.2.5 on 2025-09-06 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.FileField(upload_to='')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='institutions.institution')),
            ],
        ),
    ]
