# Generated by Django 5.2.5 on 2025-09-06 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_downloadmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadmaterial',
            name='material',
            field=models.FileField(upload_to='materials/'),
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='institutions.institution')),
            ],
        ),
    ]
