# Generated by Django 5.2.5 on 2025-09-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='stay',
            field=models.CharField(choices=[('day', 'Day'), ('boarding', 'Boarding'), ('all', 'All')], default='all', max_length=10),
        ),
    ]
